// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function GetDefaultSaveDir() {
  return window['go']['main']['App']['GetDefaultSaveDir']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HandleBrowserExtension(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HandleBrowserExtension'](arg1, arg2, arg3, arg4);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenFileFolder(arg1) {
  return window['go']['main']['App']['OpenFileFolder'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function ResumeAll() {
  return window['go']['main']['App']['ResumeAll']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
