// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:number):Promise<models.DownloadItem>;

export function CancelDownload(arg1:string):Promise<void>;

export function GetDefaultSaveDir():Promise<string>;

export function GetDownloads():Promise<Array<models.DownloadItem>>;

export function GetSettings():Promise<models.Settings>;

export function HandleBrowserExtension(arg1:string,arg2:string):Promise<models.DownloadItem>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenFileFolder(arg1:string):Promise<void>;

export function PauseAll():Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function ResumeAll():Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
